#!/usr/bin/env python


bld.SAMBA_LIBRARY('samba-security',
                  source='dom_sid.c display_sec.c secace.c secacl.c security_descriptor.c sddl.c privileges.c security_token.c access_check.c object_tree.c create_descriptor.c util_sid.c session.c secdesc.c',
                  private_library=False,
                  deps='talloc ndr NDR_SECURITY',
                  public_headers='samba_security.h',
                  pc_files='security.pc',
                  vnum='0.0.1'
                  )

bld.SAMBA_PYTHON('pysecurity',
                 source='pysecurity.c',
                 deps='samba-security pytalloc-util',
                 realname='samba/security.so'
                 )
